spring:
  application:
    name: perseus
  profiles:
    active: dev

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  access-time: 900000
  refresh-time: 604800000
  prefix: "Bearer "
  header: "Authorization"
  secret-key: ${JWT-SECRET-KEY}

auth:
  client-id : ${AUTH-CLIENT-ID}
  redirect-uri : "http://localhost:8080"